config/routes.rb
Rails.application.routes.draw do
  resources :catastrophes
  root to: "catastrophes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catastrophe.rb
class Catastrophe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catastrophes_controller.rb
class CatastrophesController < ApplicationController
  before_action :set_catastrophe, only: [:show, :edit, :update, :destroy]

  # GET /catastrophes
  # GET /catastrophes.json
  def index
    @catastrophes = Catastrophe.all
  end

  # GET /catastrophes/1
  # GET /catastrophes/1.json
  def show
  end

  # GET /catastrophes/new
  def new
    @catastrophe = Catastrophe.new
  end

  # GET /catastrophes/1/edit
  def edit
  end

  # POST /catastrophes
  # POST /catastrophes.json
  def create
    @catastrophe = Catastrophe.new(catastrophe_params)

    respond_to do |format|
      if @catastrophe.save
        format.html { redirect_to @catastrophe, notice: 'Catastrophe was successfully created.' }
        format.json { render :show, status: :created, location: @catastrophe }
      else
        format.html { render :new }
        format.json { render json: @catastrophe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catastrophes/1
  # PATCH/PUT /catastrophes/1.json
  def update
    respond_to do |format|
      if @catastrophe.update(catastrophe_params)
        format.html { redirect_to @catastrophe, notice: 'Catastrophe was successfully updated.' }
        format.json { render :show, status: :ok, location: @catastrophe }
      else
        format.html { render :edit }
        format.json { render json: @catastrophe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catastrophes/1
  # DELETE /catastrophes/1.json
  def destroy
    @catastrophe.destroy
    respond_to do |format|
      format.html { redirect_to catastrophes_url, notice: 'Catastrophe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catastrophe
      @catastrophe = Catastrophe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catastrophe_params
      params.require(:catastrophe).permit(:image, :nom, :genre, :lieu, :date, :puissance, :morts, :blesses)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catastrophes_helper.rb
module CatastrophesHelper
end

app/views/catastrophes/_form.html.erb
<%= form_with(model: catastrophe, local: true) do |form| %>
  <% if catastrophe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(catastrophe.errors.count, "error") %> prohibited this catastrophe from being saved:</h2>

      <ul>
      <% catastrophe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :lieu %>
    <%= form.text_field :lieu %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :puissance %>
    <%= form.text_field :puissance %>
  </div>

  <div class="field">
    <%= form.label :morts %>
    <%= form.number_field :morts %>
  </div>

  <div class="field">
    <%= form.label :blesses %>
    <%= form.number_field :blesses %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/catastrophes/edit.html.erb
<h1>Editing Catastrophe</h1>

<%= render 'form', catastrophe: @catastrophe %>

<%= link_to 'Show', @catastrophe %> |
<%= link_to 'Back', catastrophes_path %>

app/views/catastrophes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catastrophes</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Nom</th>
      <th>Genre</th>
      <th>Lieu</th>
      <th>Date</th>
      <th>Puissance</th>
      <th>Morts</th>
      <th>Blesses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catastrophes.each do |catastrophe| %>
      <tr>
        <td><img src="<%= catastrophe.image %>"></td>
        <td><%= catastrophe.nom %></td>
        <td><%= catastrophe.genre %></td>
        <td><%= catastrophe.lieu %></td>
        <td><%= catastrophe.date %></td>
        <td><%= catastrophe.puissance %></td>
        <td><%= catastrophe.morts %></td>
        <td><%= catastrophe.blesses %></td>
        <td><%= link_to 'Show', catastrophe %></td>
        <td><%= link_to 'Edit', edit_catastrophe_path(catastrophe) %></td>
        <td><%= link_to 'Destroy', catastrophe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catastrophe', new_catastrophe_path %>

app/views/catastrophes/new.html.erb
<h1>New Catastrophe</h1>

<%= render 'form', catastrophe: @catastrophe %>

<%= link_to 'Back', catastrophes_path %>

app/views/catastrophes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @catastrophe.image %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @catastrophe.nom %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @catastrophe.genre %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @catastrophe.lieu %>
</p>

<p>
  <strong>Date:</strong>
  <%= @catastrophe.date %>
</p>

<p>
  <strong>Puissance:</strong>
  <%= @catastrophe.puissance %>
</p>

<p>
  <strong>Morts:</strong>
  <%= @catastrophe.morts %>
</p>

<p>
  <strong>Blesses:</strong>
  <%= @catastrophe.blesses %>
</p>

<%= link_to 'Edit', edit_catastrophe_path(@catastrophe) %> |
<%= link_to 'Back', catastrophes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Museum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>